# Generated by Django 4.0 on 2021-12-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_acc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botusers',
            old_name='user_bot_id',
            new_name='chat_id',
        ),
    ]
