# Generated by Django 4.0 on 2021-12-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_acc', '0004_remove_botusers_referral_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botusers',
            name='user_id',
        ),
    ]
