# Generated by Django 4.0 on 2021-12-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_acc', '0005_remove_botusers_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botusers',
            options={'verbose_name': 'Юзер', 'verbose_name_plural': 'Юзеры'},
        ),
        migrations.AlterModelOptions(
            name='referrallinks',
            options={'verbose_name': 'Реферальная ссылка', 'verbose_name_plural': 'Реферальные ссылки'},
        ),
    ]
